services:
  postgres:
    image: postgres:17-alpine
    container_name: olomove-postgres

    environment:
      POSTGRES_DB: olomove
      POSTGRES_USER: olomove
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: